update fornt

diff --git a/sqlserver/Dockerfile b/sqlserver/Dockerfile
--- a/sqlserver/Dockerfile
+++ b/sqlserver/Dockerfile
@@ -1,35 +1,47 @@
-
 FROM mcr.microsoft.com/mssql/server:2017-latest
-MAINTAINER Lorenzo Lince<lorenzolince@gmail.com>
-# Create a config directory
-RUN mkdir -p /usr/config
+
 WORKDIR /usr/config
 
-# Bundle config source
-COPY . /usr/config
-RUN echo '#!/bin/bash' > configure-db.sh
-RUN echo 'echo $MSSQL_SA_PASSWORD' >> configure-db.sh
-RUN echo 'export STATUS=1' >> configure-db.sh
-RUN echo 'i=0' >> configure-db.sh
-RUN echo 'while [[ $STATUS -ne 0 ]] && [[ $i -lt 30 ]]; do' >> configure-db.sh
-RUN echo 'i=$i+1' >> configure-db.sh
-RUN echo 'echo "################################## MSSQL_SA_PASSWORD ####################################"' >> configure-db.sh
-RUN echo 'sleep 1' >> configure-db.sh
-RUN echo '/opt/mssql-tools/bin/sqlcmd -t 1 -U sa -P $MSSQL_SA_PASSWORD -Q "select 1" >> /dev/null' >> configure-db.sh
-RUN echo 'STATUS=$?' >> configure-db.sh
-RUN echo 'done' >> configure-db.sh
-RUN echo 'if [ $STATUS -ne 0 ]; then' >> configure-db.sh
-RUN echo 'echo "Error: MSSQL SERVER took more than thirty seconds to start up."' >> configure-db.sh
-RUN echo 'exit 1' >> configure-db.sh
-RUN echo 'fi' >> configure-db.sh
-RUN echo 'echo "======= MSSQL SERVER STARTED ========" ' >> configure-db.sh
-RUN echo '/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $MSSQL_SA_PASSWORD -i SQLSERVER_TEST.sql' >> configure-db.sh
-RUN echo 'echo "======= MSSQL CONFIG COMPLETE =======" ' >> configure-db.sh
-# Grant permissions for to our scripts to be executable
-RUN chmod +x /usr/config/entrypoint.sh
-RUN chmod +x /usr/config/configure-db.sh
-RUN ls
+COPY generate_service_sqlserver_test_suite.sql /usr/config/generate_service_sqlserver_test_suite.sql
+
+RUN printf '%s\n' \
+	'#!/bin/bash' \
+	'set -e' \
+	'SQLCMD="/opt/mssql-tools/bin/sqlcmd"' \
+	'SQLCMD_EXTRA_ARGS=""' \
+	'if [ -x /opt/mssql-tools18/bin/sqlcmd ]; then' \
+	'    SQLCMD="/opt/mssql-tools18/bin/sqlcmd"' \
+	'    SQLCMD_EXTRA_ARGS="-C"' \
+	'fi' \
+	'echo "Waiting for SQL Server..."' \
+	'STATUS=1' \
+	'i=0' \
+	'set +e' \
+	'while [ "$STATUS" -ne 0 ] && [ "$i" -lt 60 ]; do' \
+	'    i=$((i + 1))' \
+	'    "$SQLCMD" $SQLCMD_EXTRA_ARGS -t 1 -S localhost -U sa -P "$MSSQL_SA_PASSWORD" -Q "SELECT 1" >/dev/null 2>&1' \
+	'    STATUS=$?' \
+	'    if [ "$STATUS" -ne 0 ]; then sleep 1; fi' \
+	'done' \
+	'set -e' \
+	'if [ "$STATUS" -ne 0 ]; then' \
+	'    echo "Error: MSSQL SERVER took more than sixty seconds to start up."' \
+	'    exit 1' \
+	'fi' \
+	'echo "======= MSSQL SERVER STARTED ========"' \
+	'"$SQLCMD" $SQLCMD_EXTRA_ARGS -S localhost -U sa -P "$MSSQL_SA_PASSWORD" -Q "IF DB_ID(N'\''test'\'') IS NULL CREATE DATABASE [test];"' \
+	'INIT_STATUS=$("$SQLCMD" $SQLCMD_EXTRA_ARGS -S localhost -U sa -P "$MSSQL_SA_PASSWORD" -d test -h -1 -W -Q "SET NOCOUNT ON; IF OBJECT_ID(N'\''dbo.GS_PERSONA'\'', N'\''U'\'') IS NULL SELECT 0 ELSE SELECT 1;" | tr -d "[:space:]")' \
+	'if [ "$INIT_STATUS" = "1" ]; then' \
+	'    echo "generate_service_sqlserver_test_suite.sql already initialized; skipping."' \
+	'else' \
+	'    "$SQLCMD" $SQLCMD_EXTRA_ARGS -S localhost -U sa -P "$MSSQL_SA_PASSWORD" -d test -i /usr/config/generate_service_sqlserver_test_suite.sql' \
+	'fi' \
+	'echo "======= MSSQL CONFIG COMPLETE ======="' \
+	> /usr/config/configure-db.sh \
+	&& chmod +x /usr/config/configure-db.sh
+
 EXPOSE 1433
-CMD /bin/bash ./entrypoint.sh
+
+CMD /bin/bash -c "/usr/config/configure-db.sh & /opt/mssql/bin/sqlservr"
 
 
